/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.bdavanzadas.agenciafiscal_interfaces;

import javax.swing.JOptionPane;

/**
 *
 * @author rover
 */
public class PanelInicio extends javax.swing.JPanel {
    private  FramePrincipal framePrincipal;

    /**
     * Creates new form Inicio
     */
    public PanelInicio(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        lblMano = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblTexto = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblContribuyentes = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        lblTramites = new javax.swing.JLabel();
        lblLogoHacienda = new javax.swing.JLabel();
        lblLogoSonora = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setPreferredSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 260, 190, 50));

        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 180, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PantallaInicio.png"))); // NOI18N
        lblFondo.setToolTipText("");
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblMano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manoInicio.png"))); // NOI18N
        add(lblMano, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        lblBienvenido.setFont(new java.awt.Font("Montserrat", 0, 56)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(137, 21, 71));
        lblBienvenido.setText("BIENVENID@");
        add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        lblTexto.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(116, 71, 48));
        lblTexto.setText("Selecciona una opción del menú para comenzar");
        add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 480, 30));

        lblTitulo1.setFont(new java.awt.Font("Montserrat", 0, 26)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(155, 90, 23));
        lblTitulo1.setText("Red Única de Trámites");
        add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 26, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Montserrat", 1, 26)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(116, 71, 48));
        lblTitulo2.setText("Proyecto RUTRA");
        add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 66, -1, -1));

        lblContribuyentes.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblContribuyentes.setForeground(new java.awt.Color(155, 90, 23));
        lblContribuyentes.setText("Contribuyentes");
        add(lblContribuyentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 416, -1, -1));

        lblReportes.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(155, 90, 23));
        lblReportes.setText("Reportes");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 369, -1, -1));

        lblConsultas.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblConsultas.setForeground(new java.awt.Color(155, 90, 23));
        lblConsultas.setText("Consultas");
        add(lblConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 322, -1, -1));

        lblTramites.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblTramites.setForeground(new java.awt.Color(155, 90, 23));
        lblTramites.setText("Trámites");
        add(lblTramites, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 275, -1, -1));

        lblLogoHacienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoHacienda.png"))); // NOI18N
        add(lblLogoHacienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblLogoSonora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSonora.png"))); // NOI18N
        add(lblLogoSonora, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "Pene pequeño");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, "Pene grande");        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblContribuyentes;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoHacienda;
    private javax.swing.JLabel lblLogoSonora;
    private javax.swing.JLabel lblMano;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTramites;
    // End of variables declaration//GEN-END:variables
}
