/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.itson.bdavanzadas.agenciafiscal_interfaces;

/**
 *
 * @author rover
 */
public class PanelLicencia extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public PanelLicencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        lblContribuyentes = new javax.swing.JLabel();
        lblReportes = new javax.swing.JLabel();
        lblConsultas = new javax.swing.JLabel();
        lblTramites = new javax.swing.JLabel();
        lblLogoHacienda = new javax.swing.JLabel();
        lblLogoSonora = new javax.swing.JLabel();
        lblTramites1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setPreferredSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(137, 21, 71));
        lblBienvenido.setText("SOLICITAR TRÁMITE");
        add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        lblTitulo1.setFont(new java.awt.Font("Montserrat", 0, 26)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(155, 90, 23));
        lblTitulo1.setText("Red Única de Trámites");
        add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 26, -1, -1));

        lblTitulo2.setFont(new java.awt.Font("Montserrat", 1, 26)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(116, 71, 48));
        lblTitulo2.setText("Proyecto RUTRA");
        add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 66, -1, -1));

        lblContribuyentes.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblContribuyentes.setForeground(new java.awt.Color(155, 90, 23));
        lblContribuyentes.setText("Contribuyentes");
        add(lblContribuyentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 416, -1, -1));

        lblReportes.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(155, 90, 23));
        lblReportes.setText("Reportes");
        add(lblReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 369, -1, -1));

        lblConsultas.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblConsultas.setForeground(new java.awt.Color(155, 90, 23));
        lblConsultas.setText("Consultas");
        add(lblConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 322, -1, -1));

        lblTramites.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblTramites.setForeground(new java.awt.Color(255, 255, 255));
        lblTramites.setText("Regresar");
        add(lblTramites, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        lblLogoHacienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoHacienda.png"))); // NOI18N
        add(lblLogoHacienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        lblLogoSonora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoSonora.png"))); // NOI18N
        add(lblLogoSonora, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        lblTramites1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lblTramites1.setForeground(new java.awt.Color(255, 255, 255));
        lblTramites1.setText("Trámites");
        add(lblTramites1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 275, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 250, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/licenciaVista.png"))); // NOI18N
        lblFondo.setToolTipText("");
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblConsultas;
    private javax.swing.JLabel lblContribuyentes;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogoHacienda;
    private javax.swing.JLabel lblLogoSonora;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTramites;
    private javax.swing.JLabel lblTramites1;
    // End of variables declaration//GEN-END:variables
}
