package org.itson.bdavanzadas.agenciafiscal_interfaces;

/**
 *
 * @author Roberto García
 */
public class PanelConfirmarSalir extends javax.swing.JPanel {

    /** Creates new form PanelConfirmarSalir */
    public PanelConfirmarSalir() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelConfirmarSalir.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
