package org.itson.bdavanzadas.agenciafiscal_presentacion;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.BuscarTramitesBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.IBuscarTramitesBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.ReporteDTO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.TipoTramiteEnum;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.TramiteNuevoDTO;
import org.itson.bdavanzadas.agenciafiscal_persistencia.excepciones.PersistenciaException;

/**
 *
 * @author Roberto García
 */
public class PanelReportesBusqueda extends javax.swing.JPanel {

    FramePrincipal framePrincipal;
    TipoTramiteEnum tipoTramiteEnum;
    ReporteDTO reporteDTO;

    /**
     * Creates new form PanelReportesBusqueda
     */
    public PanelReportesBusqueda(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        if (framePrincipal.getTramites() != null) {
            setTextos();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramites = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnContribuyentes = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtNombres = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        cbxTipoTramite = new javax.swing.JComboBox<>();
        dpkDesde = new com.github.lgooddatepicker.components.DatePicker();
        dpkHasta = new com.github.lgooddatepicker.components.DatePicker();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramites.setBorder(null);
        btnTramites.setBorderPainted(false);
        btnTramites.setContentAreaFilled(false);
        btnTramites.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTramites.setOpaque(false);
        btnTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesActionPerformed(evt);
            }
        });
        add(btnTramites, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 261, 186, 47));

        btnConsultas.setBorder(null);
        btnConsultas.setBorderPainted(false);
        btnConsultas.setContentAreaFilled(false);
        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.setOpaque(false);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 308, 186, 47));

        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setOpaque(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 355, 186, 47));

        btnContribuyentes.setBorder(null);
        btnContribuyentes.setBorderPainted(false);
        btnContribuyentes.setContentAreaFilled(false);
        btnContribuyentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContribuyentes.setOpaque(false);
        btnContribuyentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContribuyentesActionPerformed(evt);
            }
        });
        add(btnContribuyentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 402, 186, 47));

        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 137, 40));

        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 500, 137, 40));

        txtNombres.setBackground(new java.awt.Color(250, 248, 245));
        txtNombres.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        txtNombres.setToolTipText("");
        txtNombres.setName(""); // NOI18N
        add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 391, 281, 30));

        txtApellidoPaterno.setBackground(new java.awt.Color(250, 248, 245));
        txtApellidoPaterno.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        txtApellidoPaterno.setToolTipText("");
        txtApellidoPaterno.setName(""); // NOI18N
        add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 453, 228, 30));

        txtApellidoMaterno.setBackground(new java.awt.Color(250, 248, 245));
        txtApellidoMaterno.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        txtApellidoMaterno.setToolTipText("");
        txtApellidoMaterno.setName(""); // NOI18N
        add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 453, 228, 30));

        cbxTipoTramite.setBackground(new java.awt.Color(250, 248, 245));
        cbxTipoTramite.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        cbxTipoTramite.setForeground(new java.awt.Color(30, 30, 30));
        cbxTipoTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expedición de Licencia", "Expedición de Placas" }));
        cbxTipoTramite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxTipoTramite.setMaximumSize(new java.awt.Dimension(226, 30));
        cbxTipoTramite.setName(""); // NOI18N
        add(cbxTipoTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 267, 281, 30));

        dpkDesde.setBackground(new java.awt.Color(250, 248, 245));
        dpkDesde.setFocusable(false);
        dpkDesde.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        dpkDesde.setForeground(new java.awt.Color(77, 77, 77));
        add(dpkDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 329, 219, 30));

        dpkHasta.setBackground(new java.awt.Color(250, 248, 245));
        dpkHasta.setFocusable(false);
        dpkHasta.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        dpkHasta.setForeground(new java.awt.Color(77, 77, 77));
        add(dpkHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 329, 219, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelReportesBusqueda.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (cbxTipoTramite.getSelectedItem() == null || dpkDesde.getDate() == null || dpkHasta.getDate() == null || txtNombres.getText().isBlank() || txtApellidoPaterno.getText().isBlank() || txtApellidoMaterno.getText().isBlank()) {
            framePrincipal.mostrarAviso("Es necesario llenar todos los campos\npara realizar el reporte");
        } else {
            Date desde = Date.from(dpkDesde.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
            Date hasta = Date.from(dpkHasta.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
            if (cbxTipoTramite.getSelectedIndex() == 0) {
                tipoTramiteEnum = TipoTramiteEnum.LICENCIA;

            } else {
                tipoTramiteEnum = TipoTramiteEnum.PLACAS;

            }
            reporteDTO = new ReporteDTO(
                    tipoTramiteEnum,
                    desde,
                    hasta,
                    txtNombres.getText(),
                    txtApellidoPaterno.getText(),
                    txtApellidoMaterno.getText());
            IBuscarTramitesBO buscarTramitesBO = new BuscarTramitesBO(reporteDTO);
            try {
                List<TramiteNuevoDTO> tramites = buscarTramitesBO.buscarTramites();
                framePrincipal.setTramites(tramites);
                framePrincipal.setTipoTramiteEnum(tipoTramiteEnum);
                framePrincipal.setReporteDTO(reporteDTO);
                framePrincipal.cambiarPanelReportesResultados();

            } catch (PersistenciaException e) {
                framePrincipal.mostrarAviso(e.getMessage());
            }

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        framePrincipal.setReporteDTO(null);
        framePrincipal.setTipoTramiteEnum(null);
        framePrincipal.setTramites(null);
        framePrincipal.cambiarPanelInicio();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesActionPerformed
        framePrincipal.setReporteDTO(null);
        framePrincipal.setTipoTramiteEnum(null);
        framePrincipal.setTramites(null);

        framePrincipal.cambiarPanelTramites();
    }//GEN-LAST:event_btnTramitesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        framePrincipal.setReporteDTO(null);
        framePrincipal.setTipoTramiteEnum(null);
        framePrincipal.setTramites(null);

        framePrincipal.cambiarPanelHistorialTipoBusqueda();
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        framePrincipal.setReporteDTO(null);
        framePrincipal.setTipoTramiteEnum(null);
        framePrincipal.setTramites(null);

        framePrincipal.cambiarPanelReportesBusqueda();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnContribuyentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContribuyentesActionPerformed
        framePrincipal.setReporteDTO(null);
        framePrincipal.setTipoTramiteEnum(null);
        framePrincipal.setTramites(null);

        framePrincipal.cambiarPanelContribuyentes();// TODO add your handling code here:
    }//GEN-LAST:event_btnContribuyentesActionPerformed

    private void setTextos() {
        cbxTipoTramite.setSelectedIndex(framePrincipal.getReporteDTO().getTipoTramite().equals(TipoTramiteEnum.LICENCIA) ? 0 : 1);
        dpkDesde.setDate(framePrincipal.getReporteDTO().getDesde().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        dpkHasta.setDate(framePrincipal.getReporteDTO().getHasta().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        txtNombres.setText(framePrincipal.getReporteDTO().getNombre());
        txtApellidoPaterno.setText(framePrincipal.getReporteDTO().getApellidoPaterno());
        txtApellidoMaterno.setText(framePrincipal.getReporteDTO().getApellidoMaterno());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnContribuyentes;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTramites;
    private javax.swing.JComboBox<String> cbxTipoTramite;
    private com.github.lgooddatepicker.components.DatePicker dpkDesde;
    private com.github.lgooddatepicker.components.DatePicker dpkHasta;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

}
