package org.itson.bdavanzadas.agenciafiscal_presentacion;

/**
 *
 * @author Roberto García
 */
public class PanelPlacasTipoAutomovil extends javax.swing.JPanel {

    FramePrincipal framePrincipal;

    /**
     * Creates new form PanelPlacasTipoAutomovil
     */
    public PanelPlacasTipoAutomovil(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnVehiculoNuevo = new javax.swing.JButton();
        btnVehiculoUsado = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 365, 137, 40));

        btnVehiculoNuevo.setBorder(null);
        btnVehiculoNuevo.setBorderPainted(false);
        btnVehiculoNuevo.setContentAreaFilled(false);
        btnVehiculoNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculoNuevo.setOpaque(false);
        btnVehiculoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoNuevoActionPerformed(evt);
            }
        });
        add(btnVehiculoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 258, 196, 20));

        btnVehiculoUsado.setBorder(null);
        btnVehiculoUsado.setBorderPainted(false);
        btnVehiculoUsado.setContentAreaFilled(false);
        btnVehiculoUsado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVehiculoUsado.setOpaque(false);
        btnVehiculoUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoUsadoActionPerformed(evt);
            }
        });
        add(btnVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 288, 191, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelPlacasTipoAutomovil.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        framePrincipal.cambiarPanelPlacasValidarLicencia();// TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVehiculoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoNuevoActionPerformed
        framePrincipal.cambiarPanelPlacasAgregarAutomovil();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehiculoNuevoActionPerformed

    private void btnVehiculoUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoUsadoActionPerformed
        framePrincipal.cambiarPanelPlacasBuscarAnteriores();// TODO add your handling code here:

    }//GEN-LAST:event_btnVehiculoUsadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVehiculoNuevo;
    private javax.swing.JButton btnVehiculoUsado;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
