package org.itson.bdavanzadas.agenciafiscal_presentacion;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.InsercionMasivaBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.ContribuyenteDTO;
import org.itson.bdavanzadas.agenciafiscal_persistencia.dominio.ContribuyenteDiscapacidad;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.IInsercionMasivaBO;

/**
 *
 * @author Roberto García
 */
public class PanelContribuyentes extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;

    /**
     * Creates new form panelContribuyentes
     * @param framePrincipal
     */
    public PanelContribuyentes(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTramites = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnContribuyentes = new javax.swing.JButton();
        btnAgregarContribuyentes = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTramites.setBorder(null);
        btnTramites.setBorderPainted(false);
        btnTramites.setContentAreaFilled(false);
        btnTramites.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTramites.setOpaque(false);
        btnTramites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTramitesActionPerformed(evt);
            }
        });
        add(btnTramites, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 261, 186, 47));

        btnConsultas.setBorder(null);
        btnConsultas.setBorderPainted(false);
        btnConsultas.setContentAreaFilled(false);
        btnConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultas.setOpaque(false);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        add(btnConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 308, 186, 47));

        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setOpaque(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 355, 186, 47));

        btnContribuyentes.setBorder(null);
        btnContribuyentes.setBorderPainted(false);
        btnContribuyentes.setContentAreaFilled(false);
        btnContribuyentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContribuyentes.setOpaque(false);
        add(btnContribuyentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 402, 186, 47));

        btnAgregarContribuyentes.setBorder(null);
        btnAgregarContribuyentes.setBorderPainted(false);
        btnAgregarContribuyentes.setContentAreaFilled(false);
        btnAgregarContribuyentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarContribuyentes.setOpaque(false);
        btnAgregarContribuyentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContribuyentesActionPerformed(evt);
            }
        });
        add(btnAgregarContribuyentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 213, 137, 65));

        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setOpaque(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 238, 137, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelContribuyentes.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTramitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTramitesActionPerformed
        framePrincipal.cambiarPanelTramites();
    }//GEN-LAST:event_btnTramitesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAgregarContribuyentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContribuyentesActionPerformed
        if (framePrincipal.mostrarConfirmacion("¿Seguro que deseas agregar 20 contribuyentes de prueba?", "Agregar contribuyentes")) {
            agregarContribuyentes();
            framePrincipal.mostrarInformacion("Registros agregados exitosamente", "Éxito");
            framePrincipal.cambiarPanelInicio();
        }
    }//GEN-LAST:event_btnAgregarContribuyentesActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        framePrincipal.cambiarPanelInicio();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private static void agregarContribuyentes() {
        List<ContribuyenteDTO> contribuyentesDTO = new ArrayList<>();

        // Generar 20 registros hardcodeados
                contribuyentesDTO.add(new ContribuyenteDTO("RFC1234567890", "Juan", "Perez", "Garcia", "1234567890", new Date(1985 - 1900, 5, 20), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC2345678901", "Maria", "Lopez", "Martinez", "2345678901", new Date(1978 - 1900, 9, 12), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC3456789012", "Pedro", "Gomez", "Rodriguez", "3456789012", new Date(1963 - 1900, 2, 5), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC4567890123", "Ana", "Hernandez", "Gonzalez", "4567890123", new Date(1955 - 1900, 11, 30), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC5678901234", "Luis", "Diaz", "Perez", "5678901234", new Date(1992 - 1900, 7, 14), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC6789012345", "Laura", "Martinez", "Sanchez", "6789012345", new Date(1980 - 1900, 4, 8), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC7890123456", "Carlos", "Torres", "Lopez", "7890123456", new Date(1974 - 1900, 1, 23), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC8901234567", "Sofia", "Ramirez", "Herrera", "8901234567", new Date(1968 - 1900, 6, 17), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC9012345678", "Daniel", "Ruiz", "Jimenez", "9012345678", new Date(1998 - 1900, 10, 3), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC1234013489", "Elena", "Gutierrez", "Torres", "0123456789", new Date(1979 - 1900, 8, 26), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC5748963254", "Alejandro", "Luna", "Vazquez", "1234567890", new Date(1957 - 1900, 3, 19), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC1315467821", "Monica", "Castro", "Nunez", "2345678901", new Date(1969 - 1900, 12, 7), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC4613758912", "Jorge", "Mendez", "Flores", "3456789012", new Date(1987 - 1900, 2, 10), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC0024361579", "Fernanda", "Rojas", "Santos", "4567890123", new Date(1972 - 1900, 5, 25), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC6431985734", "Pablo", "Vargas", "Montes", "5678901234", new Date(1995 - 1900, 9, 3), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC6789034618", "Eva", "Molina", "Cruz", "6789012345", new Date(1983 - 1900, 11, 8), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC7167436577", "Hector", "Cruz", "Dominguez", "7890123456", new Date(1960 - 1900, 7, 16), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC0145675157", "Adriana", "Flores", "Ramirez", "8901234567", new Date(1990 - 1900, 1, 12), ContribuyenteDiscapacidad.SI));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC6451375479", "Raul", "Santiago", "Guerrero", "9012345678", new Date(1976 - 1900, 4, 5), ContribuyenteDiscapacidad.NO));
        contribuyentesDTO.add(new ContribuyenteDTO("RFC6476721470", "Carmen", "Mendez", "Ortega", "0123456789", new Date(1988 - 1900, 8, 28), ContribuyenteDiscapacidad.SI));

        IInsercionMasivaBO insercion = new InsercionMasivaBO();

        insercion.insertar(contribuyentesDTO);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarContribuyentes;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnContribuyentes;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTramites;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
