package org.itson.bdavanzadas.agenciafiscal_presentacion;

/**
 *
 * @author Roberto García
 */
public class PanelHistorialTipoBusqueda extends javax.swing.JPanel {

    FramePrincipal framePrincipal;
    /** Creates new form PanelHistorialBusqueda */
    public PanelHistorialTipoBusqueda(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnRfc = new javax.swing.JButton();
        btnNombre = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 417, 137, 40));

        btnRfc.setBorder(null);
        btnRfc.setBorderPainted(false);
        btnRfc.setContentAreaFilled(false);
        btnRfc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRfc.setOpaque(false);
        btnRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRfcActionPerformed(evt);
            }
        });
        add(btnRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 288, 167, 20));

        btnNombre.setBorder(null);
        btnNombre.setBorderPainted(false);
        btnNombre.setContentAreaFilled(false);
        btnNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNombre.setOpaque(false);
        btnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNombreActionPerformed(evt);
            }
        });
        add(btnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 318, 203, 20));

        btnFecha.setBorder(null);
        btnFecha.setBorderPainted(false);
        btnFecha.setContentAreaFilled(false);
        btnFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFecha.setOpaque(false);
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });
        add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 348, 315, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelHistorialTipoBusqueda.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        framePrincipal.cambiarPanelInicio();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfcActionPerformed
        framePrincipal.cambiarPanelHistorialRfc();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRfcActionPerformed

    private void btnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNombreActionPerformed
        framePrincipal.cambiarPanelHistorialNombre();
    }//GEN-LAST:event_btnNombreActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        framePrincipal.cambiarPanelHistorialFecha();
    }//GEN-LAST:event_btnFechaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnNombre;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRfc;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
