package org.itson.bdavanzadas.agenciafiscal_presentacion;

import java.util.List;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.BuscarPorRfcBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.BuscarTramitesBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.IBuscarPorRfcBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.bos.IBuscarTramitesBO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.BuscarContribyenteRFCDTO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.ContribuyenteDTO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.LicenciaNuevaDTO;
import org.itson.bdavanzadas.agenciafiscal_negocio.dtos.PlacasNuevasDTO;
import org.itson.bdavanzadas.agenciafiscal_negocio.excepciones.ValidacionDTOException;
import org.itson.bdavanzadas.agenciafiscal_persistencia.excepciones.PersistenciaException;

/**
 *
 * @author Roberto García
 */
public class PanelHistorialRfc extends javax.swing.JPanel {

    FramePrincipal framePrincipal;

    /**
     * Creates new form PanelHistorialRfc
     */
    public PanelHistorialRfc(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtRfc = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1000, 580));
        setMinimumSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 338, 137, 40));

        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 338, 137, 40));

        txtRfc.setBackground(new java.awt.Color(250, 248, 245));
        txtRfc.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        txtRfc.setToolTipText("");
        txtRfc.setName(""); // NOI18N
        add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 278, 250, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelHistorialRfc.png"))); // NOI18N
        add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        framePrincipal.setPanelAnterior(null);

        framePrincipal.cambiarPanelHistorialTipoBusqueda();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtRfc.getText().isBlank()) {
            framePrincipal.mostrarAviso("El campo de RFC no puede estar vacío");
        } else {
            BuscarContribyenteRFCDTO contribuyenteRfcDto = new BuscarContribyenteRFCDTO(txtRfc.getText());
            IBuscarPorRfcBO buscarPorRfcBO = new BuscarPorRfcBO(contribuyenteRfcDto);
            try {
                ContribuyenteDTO contribuyenteDTO = buscarPorRfcBO.buscarContribuyente();
                IBuscarTramitesBO buscarTramitesBO = new BuscarTramitesBO();
                List<LicenciaNuevaDTO> licenciasDTO = buscarTramitesBO.buscarLicencias(contribuyenteDTO);
                List<PlacasNuevasDTO> placasDTO = buscarTramitesBO.buscarPlacas(contribuyenteDTO);
                
                framePrincipal.setContribuyenteDTO(contribuyenteDTO);
                framePrincipal.setPanelAnterior(1);
                framePrincipal.mostrarInformacion("Contribuyente found", "Exito");
                framePrincipal.cambiarPanelHistorialSeleccion();
            } catch (ValidacionDTOException | PersistenciaException e) {
                framePrincipal.mostrarAviso(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables

}
